# Generated by Django 2.1.15 on 2023-02-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('student_Id', models.CharField(max_length=30)),
                ('mail_Id', models.CharField(max_length=30)),
                ('submit_date', models.DateTimeField(verbose_name='release date')),
                ('genre', models.CharField(max_length=500)),
                ('summary', models.CharField(max_length=500)),
            ],
        ),
    ]
