# Generated by Django 2.1.15 on 2023-02-23 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj_idea', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='ProjIdea',
        ),
    ]
